---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`volumen` es una variable local"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`volumen` es una variable global"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`subirVolumen` es una función"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`subirVolumen` es un procedimiento"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`bajarVolumen` es una función"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`bajarVolumen` es un procedimiento"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`esVolumenSaludable` es una función"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`esVolumenSaludable` es un procedimiento"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`subirVolumen` retorna un número"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`esVolumenSaludable` retorna un número"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`esVolumenSaludable` retorna un booleano"
  checked: true
name: Bajemos el volumen
