---
locale: es
tags: []
layout: input_bottom
editor: 0
type: playground
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_fails
name: Esto no tiene valor
